### ISSUE TITLE
Videostream crashes when PCMD buffer is empty

### ISSUE THREAD

**Issue by Zepheus** [ARDroneSDK3/libARStream#1]
This issue is Bebop related, but not sure if it's shared between all ArDrone3 products.
When videostream is enabled and no intermediate PCMD commands of (0,0,0,0) are sent at a fixed time interval, the videostream crashes as soon as a non-zero PCMD command is sent. (e.g. stream video, take off, rotate right/left).

I assume this is because there is some internal caching of the latest PCMD commands for video stabilization & that this buffer does not get bound checked if it's not full yet. Currently, I use a workaround by sending zero-PCMD commands at a fixed time interval while the drone is idle/hovering, but this is not expected behaviour. 

Also, there's a noticable delay/hiccup on video when rotating, even with the official app.

Kind regards
Cedric

**Comment by N-Bz** [comment]
Hi,

This is the normal behavior of the devices (both on Bebop and on Jumping sumo).
You can find some explanations [here](https://github.com/ARDroneSDK3/Samples/issues/11), but the basic idea is that your "workaround" is actually the proper way to do.

Regards,
Nicolas.

**Comment by Zepheus** [comment]
I understand some packets are needed for wifi quality estimation, but I would assume that the ping messages are used for this (since they inherently are sent at a fixed time interval). Is there any reason PCMD commands are used for this estimator? I can do a flip just fine at a higher framerate so it seems sort of strange that it can't handle the video throughput for a simple rotation.

**Comment by N-Bz** [comment]
We use the PCMD as the source of the estimator because they're the most important commands during flight (And because the job of the estimator is to make sure that these commands are not blocked by the video, as a wifi link is in fact half-duplex).

We could use any other periodic commands, but tests proved that using the PCMD commands directy gave a better reaction time (lowering the bandwidth of the video when the wifi quality lowers, so the piloting is still possible) than other tested methods.

Regards,
Nicolas.

**Comment by Zepheus** [comment]
Thank you for your fast response.
It's not an intuitive solution, but I understand the reasons behind it.
Perhaps this should made be more clear in the documentation.

Kind regards,
Cedric
